import { Button } from "@/components/ui/button";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
      >
       
       <body className="min-h-full">
        <div className="flex min-h-screen flex-col">
          <header className="flex h-14 shrink-0 items-center justify-between border-b border-border bg-card px-6">
            <Link href="/" className="text-lg font-semibold text-foreground">
              CodeCritic
            </Link>

            <div className="flex items-center gap-3">
              <Button asChild size="sm">
                <Link href="/submissions/new">New submission</Link>
              </Button>

              <Show
                when="signed-in"
                fallback={
                  <div className="flex gap-2">
                    <SignInButton mode="modal">
                      <Button variant="ghost" size="sm">
                        Sign in
                      </Button>
                    </SignInButton>
                    <SignUpButton mode="modal">
                      <Button size="sm">Sign up</Button>
                    </SignUpButton>
                  </div>
                }
              >
                <UserButton />
              </Show>
            </div>
          </header>

          <div className="grid flex-1 grid-cols-[220px_1fr]">
            <aside className="border-r border-sidebar-border bg-sidebar px-4 py-6">
              <nav className="flex flex-col gap-1">
                <Link
                  href="/"
                  className="rounded-md px-3 py-2 text-sm font-medium text-sidebar-foreground hover:bg-sidebar-accent"
                >
                  Feed
                </Link>
              </nav>
            </aside>

            <main className="flex flex-col">{children}</main>
          </div>
        </div>
      </body>
      </html>
    </ClerkProvider>
  );
}
